import unittest

from google.cloud import firestore

from gravitate import main as main
from gravitate.domain.event.dao import EventDao
from gravitate.domain.event.models import Event
from test.store import getEventDict
from test.test_main import getMockAuthHeaders


class UserEventServiceTest(unittest.TestCase):

    maxDiff = None

    def setUp(self):
        main.app.testing = True
        self.app = main.app.test_client()

    def test_post(self):
        fb_dict = {
            "description": "Advance Sale begins Friday, 6/1 at 11AM PDT\nwww.coachella.com",
            "end_time": "2019-04-14T23:59:00-0700",
            "name": "Coachella Valley Music and Arts Festival 2019 - Weekend 1",
            "place": {
                "name": "Coachella",
                "location": {
                    "latitude": 33.679974,
                    "longitude": -116.237221
                },
                "id": "20281766647"
            },
            "start_time": "2019-04-12T12:00:00-0700",
            "id": "137943263736990"
        }
        r = self.app.post(path='/me/events',
                          headers=getMockAuthHeaders(),
                          json=fb_dict
                         )
        result = r.json
        print(result)

    def test_post_twice(self):
        """
        Test that posting the same event twice returns the same id
        :return:
        """
        fb_dict = {
            "description": "Advance Sale begins Friday, 6/1 at 11AM PDT\nwww.coachella.com",
            "end_time": "2019-04-14T23:59:00-0700",
            "name": "Coachella Valley Music and Arts Festival 2019 - Weekend 1",
            "place": {
                "name": "Coachella",
                "location": {
                    "latitude": 33.679974,
                    "longitude": -116.237221
                },
                "id": "20281766647"
            },
            "start_time": "2019-04-12T12:00:00-0700",
            "id": "137943263736990"
        }
        r = self.app.post(path='/me/events',
                          headers=getMockAuthHeaders(),
                          json=fb_dict
                          )
        result = r.json
        id_1 = result["id"]
        r = self.app.post(path='/me/events',
                          headers=getMockAuthHeaders(),
                          json=fb_dict
                          )
        result = r.json
        id_2 = result["id"]
        self.assertEqual(id_1, id_2)


class EventServiceTest(unittest.TestCase):

    maxDiff = None

    def setUp(self):
        event_dict = getEventDict(use_firestore_ref=True,
                                  to_earliest=1545033600,
                                  to_latest=1545119999,
                                  from_earliest=1545033600,
                                  from_latest=1545119999)
        self.event = Event.from_dict(event_dict)
        self.refs_to_delete = list()

        main.app.testing = True
        self.app = main.app.test_client()
        self.userId = "testuid1"

        event_ref: firestore.DocumentReference = EventDao().create(self.event)
        self.event.set_firestore_ref(event_ref)
        self.refs_to_delete.append(event_ref)
        self.event_id = event_ref.id

    def testGet(self):
        """
        Note that test data generated by getEventDict has a 9AM-11AM range
        :return:
        """
        r = self.app.get(path='/events' + '/' + self.event_id,
                         headers=getMockAuthHeaders()
                         )

        dict_expected = {
            'eventCategory': "airport",
            'participants': [],
            'airportCode': "LAX",
            'earliestArrival': "2018-12-17T00:00:00",
            'earliestDeparture': '2018-12-17T00:00:00',
            'latestArrival': "2018-12-17T23:59:59",
            'latestDeparture': "2018-12-17T23:59:59",
            'pricing': 100,
            'locationId': "testairportlocationid1",
            'isClosed': False
        }

        result = dict(r.json)

        self.assertEqual(r.status_code, 200, "GET is successful")
        # print(result)
        self.assertDictContainsSubset(dict_expected, result)

    def tearDown(self):
        for ref in self.refs_to_delete:
            ref.delete()
        self.refs_to_delete.clear()

